---
title: "De Mark Sequential"
format: html
---

DeMark sequential has 2 stages.  The TD Setup and TD Countdown. 

# Intro 

```{r}
#| warning: false
#| message: false

library(dplyr)      # rename(), arrange(), select(), if_else(), distinct()
library(readr)      # read_csv()
library(lubridate)  # today()
library(purrr)      # map()
library(tidyr)      # drop_na

the_path <- here::here()

# load up the data in a clean way 
conform_data <- function(ticker) {
    df <- read_csv(paste0(the_path, "/data_stock_fmpr/", ticker, ".csv"), 
                   show_col_types = FALSE) |> 
      rename(index = date, adjusted = adjClose) |> 
      arrange(index) |> 
      select(index, close, high, low) |> 
      mutate(close_greater_than_4earlier = if_else(close > lag(close, 4), 1, 0), 
             close_less_than_4earlier = if_else(close < lag(close, 4), 1, 0), 
             close_greater_than_high_2earlier = if_else(close > lag(high, n=2), 1, 0), 
             close_less_than_low_2earlier = if_else(close < lag(low, n=2), 1, 0)) |> 
      drop_na() |> filter(index > (today() - 1000))
  return(df)
}

### TD Bearish Price Flip occurs when 
# * the market records a close greater than the close four bars earlier, 
# * immediately followed by a close less than the close four bars earlier. 
bearish_price_flip <- function(df) { 
  yo <- df |> 
    mutate(bearish_price_flip = if_else(
      close < lag(close, 4) & lag(close_greater_than_4earlier) == 1, 
      1, 0))
  return(yo)
}

### TD Buy Setup - After a bearish price flip, 
# * there must be nine consecutive closes, each one less than the corresponding close four bars earlier. 
buy_setup <- function(df) {
  yo <- df |> 
    group_by(grp_buy_setup = cumsum(close_less_than_4earlier == 0 | bearish_price_flip == 1)) |> 
    mutate(TD_buy_setup = if_else(cumsum(bearish_price_flip)>0, cumsum(close_less_than_4earlier), 0)) |> 
    ungroup()
  return(yo)
}

### Once a TD Buy Setup successfully reaches nine, the first phase of TD Sequential is complete, and a TD Buy Countdown can begin.

#####################################################################
#####################################################################
# TD Sequential Sell - Phase 1
###  before a TD Sell Countdown can begin, we need to see a bullish: TD Price Flip + TD Sell Setup

# TD Bullish Price Flip
### A Bullish TD Price Flip occurs when the market records a close less than the close four bars before, immediately followed by a close greater than the close four bars earlier.
bullish_price_flip <- function(df) { 
  yo <- df |> 
    mutate(bullish_price_flip = if_else(
      close > lag(close, 4) & lag(close_less_than_4earlier) == 1, 
      1, 0))
  return(yo)
}

# TD Sell Setup
### Once the bullish TD Price Flip occurs, a TD Sell Setup, consisting of nine consecutive closes, each one greater than the corresponding close four bars earlier, can begin
sell_setup <- function(df) {
  yo <- df |> 
    group_by(grp_sell_setup = cumsum(close_greater_than_4earlier == 0 | bullish_price_flip == 1)) |>  
    mutate(TD_sell_setup = if_else(cumsum(bullish_price_flip)>0, cumsum(close_greater_than_4earlier), 0)) |> 
    #mutate(low_within_sell_setup = slice_min(low, n=1, order_by = low)) |> 
    ungroup() 
  return(yo)
}

## WITH THE COUNTDOWN --- ISSUE to fIX
## buy countdown only start if buy setup is at 9.  It should not start if sell setup is at 9!!!
buy_countdown <- function(df) { 
  yo <- df |> 
    group_by(grp_buy_countdown = cumsum(TD_buy_setup == 9) )|> 
    mutate(TD_buy_countdown = if_else(cumany(TD_sell_setup == 9), 0, 
                                             cumsum(close_less_than_low_2earlier))) |> 
    ungroup()
  return(yo)
}

## WITH THE COUNTDOWN --- ISSUE to fIX
## sell countdown only start if sell setup is at 9.  It should not start if buy setup is at 9!!!
sell_countdown <- function(df) { 
  yo <- df |> 
    group_by(grp_sell_countdown = cumsum(TD_sell_setup == 9)) |> 
    mutate(TD_sell_countdown = if_else(cumany(TD_buy_setup == 9), 0, 
                                       cumsum(close_greater_than_high_2earlier))) |> 
    ungroup()
  return(yo)
}


## Check for TDST (TD Setup Trend). 
## On the sell setup, when it brakes the high of #1 of the previous full buy setup. 
## on the buy setup, when it brakes the low of #1 of the previous full sell setup. 
## if it brakes, then we go on a TD Countdown13. 

# Putting everything back into one function 
demark_signals<- function(ticker) {
  yo <- conform_data(ticker) |> bullish_price_flip() |> bearish_price_flip() |> 
    na.omit() |> 
    sell_setup() |> buy_setup() |> sell_countdown() |> buy_countdown() |> 
    select(index, close, high, buPF = bullish_price_flip,  sell_setup = TD_sell_setup, 
           sell_ctdown = TD_sell_countdown, 
           bePF = bearish_price_flip, buy_setup = TD_buy_setup, 
           buy_ctdown = TD_buy_countdown) |> 
    filter(index > (today() - 21)) |> 
    arrange(desc(index))
  return(yo)
}

```

```{r}
df2 <- conform_data('KMB') |> bullish_price_flip() |> bearish_price_flip() |> na.omit() |> 
  sell_setup() |> buy_setup() |> sell_countdown() |> buy_countdown() |> 
  select(index, close, high, buPF = bullish_price_flip,  sell_setup = TD_sell_setup, 
         sell_ctdown = TD_sell_countdown, 
         bePF = bearish_price_flip, buy_setup = TD_buy_setup, 
         buy_ctdown = TD_buy_countdown)
```


Our universe to understand. 

Make a list of going short (with )

```{r}
xlc = c('META', 'GOOG', 'T', 'VZ', 'DIS', 'CHTR', 'NFLX', 'CMCSA', 'EA', 'WBD', 
        'DASH', 'Z', 'PINS', 'TTD', 'TTWO', 'OMC',  'LYV', 'IPG', 'MTCH', 'FOXA', 'PARA')
xle = c('XOM', 'CVX', 'EOG', 'COP', 'MPC', 'PSX', 'PXD', 'SLB', 'VLO', 'WMB', 'OKE', 
        'OXY', 'LNG', 'HES', 'KMI', 'BKR', 'HAL', 'DVN', 'FANG', 'TRGP', 'AMR', 'MRO', 
        'EQT', 'OVV', 'FCG') 
xlf = c('BRK.B', 'JPM', 'V', 'MA', 'BAC', 'WFC', 'SPGI', 'GS', 'MS', 'BLK', 'AXP', 'SCHW', 
        'C', 'MMC', 'BX', 'PGR', 'CB', 'USB', 'PYPL', 'MCO', 'PNC', 'AON', 'TRV', 
        'CBOE', 'CME', 'ICE', 'KRE') 
xme = c('AA', 'X', 'MP', 'CLF', 'ATI', 'AMR', 'FCX', 'NUE', 'CRS', 'NEM', 'RS', 
        'STLD', 'BTU', 'HL', 'RGLD', 'GOLD', 'AEM', 'UEC', 'ALB', 'PAAS', 
        'FMC', 'MOS', 'SQM', 'PBR', 'RIO', 'VALE', 'TECK', 'SCCO', 'BHP') 
xlk = c('ABNB', 'GOOG', 'META', 'AAPL', 'NFLX', 'SQ', 'PYPL', 'TSLA', 'TWLO', 'AMZN', 
        'BABA', 'AVGO', 'ADBE', 'CRM', 'AMD', 'ACN', 'CSCO', 'INTC', 'TSM', 'MSFT', 
        'TER',  
        'ORCL', 'INTU', 'QCOM', 'IBM', 'NOW', 'TXN', 'AMAT', 'NVDA', 'PANW', 'PLTR') 

df_sell <- tibble(tickers = c(xlc, xle, xlf, xme, xlk)) |> 
  distinct() |> arrange(tickers) |> 
  mutate(demark_indicator = map(tickers, demark_signals, .progress = T)) |>
  unnest(cols = c(demark_indicator)) |> 
  arrange(desc(index), desc(sell_ctdown)) #|> filter(index > (today()-1))

df_buy <- df_sell |> 
  arrange(desc(index), desc(buy_setup))
```



```{r}
# trying shit... to delete

yo <- conform_data('AAPL') |> 
  bearish_td_price_flip() |> bullish_td_price_flip() |> drop_na() |> 
  td_buy_setup() |> td_sell_setup() |> 
  select(index, close, TD_buy_setup, TD_sell_setup) |> 
  arrange(desc(index)) |> filter(index > (today() - 300))

# dealing with TD buy setup
# problem I am facing is that it counts any close less than 4 earlier as new group 

library(ggplot2)
ggplot(yo, aes(index, close)) + 
  geom_line() + 
  geom_point(data = yo |> filter(TD_buy_setup > 7), aes(x = index, y = close), color='green') + 
  geom_point(data = yo |> filter(TD_sell_setup > 7), aes(x = index, y = close), color='red') + 
  geom_text(data = yo |> filter(TD_buy_setup > 7), 
            aes(x = index, y = close, label = TD_buy_setup), 
            color='chartreuse4', nudge_y = .25, size = 3) + 
  geom_text(data = yo |> filter(TD_sell_setup > 7), 
            aes(x = index, y = close, label = TD_sell_setup), 
            color='red', nudge_y = .25, size = 3)
  
  
```


