---
title: "Analysis of Model V01"
format: 
  html: 
    toc: true
    toc-depth: 2
    toc-location: left
    theme: darkly
    fontsize: 1.1em
    grid: 
      sidebar-width: 0px
      body-width: 2000px
      margin-width: 0px
---

We are analysis all variables here, checking predictions certainties, checking future predictions, checking metrics, etc. 

```{r}
#| label: setup
#| warning: false
#| message: false

source('../functions/model_v01a.R')
source('../functions/model_v01e.R')

library(readr)
library(dplyr)
library(purrr)
library(tidyr)
library(glue)
library(gt)

the_path <- here::here()

df <- tibble(ticker = c('AAPL', 'AMD', 'AXP', 'CVX', 'FDX', 'HAL', 'SBUX', 'YUM'))

get_var_imp <- function(ticker) {
  df <- read_csv(glue(yop, ticker, '.csv'), show_col_types = FALSE) |> 
    arrange(desc(Importance)) |> 
    mutate(rank_order = row_number())
  return(df)
}

get_metrics_class <- function(ticker, model_name) {
  df <- read_csv(glue(yop, ticker, '.csv'), show_col_types = FALSE) |> 
    slice_head(n=3)
  df2 <- tibble(name = model_name, 'Precision' = mean(df$mean_preci), 
                'SoftPreci' = mean(df$mean_soft_preci), 
                'Accuracy' = mean(df$mean_soft_acc), 
                'Recall' = mean(df$mean_recall))
  return(df2)
}

get_metrics_reg <- function(ticker, model_name) {
  df <- read_csv(glue(yop, ticker, '.csv'), show_col_types = FALSE) |> 
    slice_head(n=3)
  df2 <- tibble(name = model_name, 'RMSE' = mean(df$mean))
  return(df2)
}
```

# Analyzing Variable Importance 

## Standard with xgboost and tidymodel 

### 29 days (1 1/2 months forward) 

```{r}
#| label: varimp-29d
#| eval: false
#| echo: false

num_days = '29d'

yop <- glue(the_path, '/models/model_vars_imp/xgboost_v01a_', num_days, '_')
df_VI_v01a <- df |> 
  mutate(var_imp = map(ticker, get_var_imp)) |> 
  unnest(cols = c(var_imp)) |> 
  group_by(Variable) |> 
  summarise(mean_rank = mean(rank_order), 
            mean_imp = mean(Importance, na.rm=TRUE), 
            sd_imp = sd(Importance, na.rm=TRUE)) |> 
  arrange(desc(mean_imp))

df_VI_v01a |> gt()


yop <- glue(the_path, '/models/model_vars_imp/xgboost_v01e_', num_days, '_')
df_VI_v01e <- df |> 
  mutate(var_imp = map(ticker, get_var_imp)) |> 
  unnest(cols = c(var_imp)) |> 
  group_by(Variable) |> 
  summarise(mean_rank = mean(rank_order), 
            mean_imp = mean(Importance, na.rm=TRUE), 
            sd_imp = sd(Importance, na.rm=TRUE)) |> 
  arrange(desc(mean_imp))

df_VI_v01e |> gt()

df_VI <- df_VI_v01a |> add_row(df_VI_v01e ) |> 
  arrange(mean_rank)
```


### 41 days (2 months forward) 

```{r}
#| label: varimp-41d
#| echo: false

num_days = '41d'
yop <- glue(the_path, '/models/model_vars_imp/xgboost_v01a_', num_days, '_')

df_VI_v01a <- df |> 
  mutate(var_imp = map(ticker, get_var_imp)) |> 
  unnest(cols = c(var_imp)) |> 
  group_by(Variable) |> 
  summarise(mean_rank = mean(rank_order), 
            mean_imp = mean(Importance, na.rm=TRUE), 
            sd_imp = sd(Importance, na.rm=TRUE)) |> 
  arrange(desc(mean_imp)) |> mutate(model = 'v01a')

df_VI_v01a |> gt()


yop <- glue(the_path, '/models/model_vars_imp/xgboost_v01e_', num_days, '_')

df_VI_v01e <- df |> 
  mutate(var_imp = map(ticker, get_var_imp)) |> 
  unnest(cols = c(var_imp)) |> 
  group_by(Variable) |> 
  summarise(mean_rank = mean(rank_order), 
            mean_imp = mean(Importance, na.rm=TRUE), 
            sd_imp = sd(Importance, na.rm=TRUE)) |> 
  arrange(desc(mean_imp)) |> mutate(model = 'v01e')

df_VI_v01e |> gt()

df_VI <- df_VI_v01a |> add_row(df_VI_v01e ) |> 
  arrange(mean_rank)
df_VI |> gt()
```


# Making prediction 

```{r}
#| label: makingPrediction
#| warning: false
#| message: false
#| eval: true

library(broom)
library(tidyr)
library(parsnip)
library(yardstick)

ticker <- 'HAL'
num_days <- '41d'

yop <- glue(the_path, '/models/model_raw/xgboost_v01a_', num_days, '_')
model_v01a <- read_rds(glue(yop, ticker, '.rda'))
df_v01a <- augment(model_v01a, 
                   model01a(ticker, num_days) |> filter(date > '2023-06-30')) |> 
  select(date, close, forw_ret, ord_class, v01a_class = .pred_class, 
         v01a_class1 = .pred_1, v01a_class2 = .pred_2, v01a_class3 = .pred_3)

yop <- glue(the_path, '/models/model_raw/xgboost_v01e_', num_days, '_')
model_v01e <- read_rds(glue(yop, ticker, '.rda'))
df_v01e <- augment(model_v01e, 
                   model01e(ticker, num_days) |> filter(date > '2023-06-30')) |> 
  select(date, close, forw_ret, v01e_class = ord_class, 
         v01e_pred = .pred)

yo <- left_join(df_v01a, df_v01e) |> arrange(date) 

yo |> drop_na() |> slice_tail(n = 10) |> gt()

yo |> slice_tail(n = 10) |> gt()


conf_mat(yo |> drop_na(), truth = ord_class, estimate = v01a_class)
summary(conf_mat(yo |> drop_na(), truth = ord_class, estimate = v01a_class)) |> gt()

#f_meas(yo, truth = ord_class, estimate = .pred_class)
```

